version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    # volumes:
    #   - type: bind
    #     source: ./elasticsearch/data
    #     target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=project04-es
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=false
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: ./logstash/pattern/nginx.pattern
        target: /usr/share/logstash/pattern/nginx.pattern
        read_only: true
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:${ELK_VERSION}
    ports:
      - "5601:5601"
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.hosts=elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: beats/filebeat-nginx/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./beats/filebeat-nginx/log
        target: /var/log
    ports:
      - "8080:80"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
      - logstash

networks:
  elk:
    driver: bridge